import type { Manifest } from '@core';
import type { BoardDef, ExpansionBoardCatalog } from '@core';
import { generateMajiControlConfig } from "./generators/routes";
import { generateHardware } from "./generators/hardware";
import { generateSensors } from "./generators/sensors";
import { generateBoardPackage } from "./generators/board-package";
import { generateDeviceYaml } from "./generators/device-yaml";
import { generateControl } from "./generators/control";
import { generateMqtt } from "./generators/mqtt";
import { generateAutomationEngineConfig } from "./generators/automation-engine";
import { generateCoordination } from "./generators/coordination";
import { generateTimeSync, generateTimeSyncHeader } from "./generators/time-sync";
import { generateLocalInputs } from "./generators/local-inputs";
import { generateLocalUiYaml, generateLocalUiAssetsHeader } from "./generators/local-ui";

import { collectEntityCodegen } from "./generators/collect";
import { LOGO_SVG, FIRMWARE_COMPONENT_FILES } from '@core';
import { type GeneratorId, type SecretsMap, type GenerationMetadata } from './backends/types';

export interface GeneratedFile {
  relativePath: string;
  description: string;
  content: string;
}

export interface GenerateOptions {
  /**
   * Raw site topology JSON — embedded (gzipped) as the /topology.json asset of
   * the local-UI bundle when the topology's local.ui flag is on, so the
   * on-device dashboard boots from the exact site it was generated for.
   */
  topologyJson?: string;
  /**
   * Prebuilt local-UI asset table. The browser build pipeline uses this to make
   * the firmware version and the emitted header depend on the exact same bytes,
   * without fetching `/device-ui/` twice (and risking a deploy between reads).
   */
  localUiAssetsHeader?: string;
}

/**
 * Pinned ESPHome version. The bundle vendors external_components that bind to ESPHome's
 * C++ component API, which shifts across releases — an unpinned bump can break the build.
 * Shipped as requirements.txt and soft-checked in compile.sh. Bump deliberately, with a
 * compile smoke. Keep in sync with the version a CI compile job installs.
 */
const ESPHOME_VERSION = '2026.3.1';

export { type GeneratorId, type SecretsMap, type GenerationMetadata } from './backends/types';

/** Convenience helper for tests — creates a valid GenerationMetadata with defaults. */
export function createTestMetadata(overrides?: Partial<GenerationMetadata>): GenerationMetadata {
  return {
    configSha: 'testsha000000000',
    version: 'testver1',
    siteId: 'test-site',
    controllerId: 'default',
    schemaVersion: 16,
    buildTimestamp: 0,
    appVersion: '0.0.0',
    mode: 'managed',
    brokerAddress: '127.0.0.1',
    brokerPort: 1883,
    brokerTls: false,
    brokerCa: '',
    ...overrides,
  };
}

/** Cryptographically-random bytes via Web Crypto (browser + Node 19+). */
function randomBytes(n: number): Uint8Array {
  const b = new Uint8Array(n);
  globalThis.crypto.getRandomValues(b);
  return b;
}

function toBase64(bytes: Uint8Array): string {
  let s = '';
  for (const byte of bytes) s += String.fromCharCode(byte);
  return btoa(s);
}

function toHex(bytes: Uint8Array): string {
  return Array.from(bytes, (b) => b.toString(16).padStart(2, '0')).join('');
}

export function generateDefaultSecrets(): SecretsMap {
  return {
    ota_password: toHex(randomBytes(16)),
    mqtt_token: toBase64(randomBytes(32)),
    udp_key: toHex(randomBytes(32)),
  };
}

function generateSecretsYaml(m: Manifest, secrets?: SecretsMap): string {
  const s = secrets ?? generateDefaultSecrets();
  return [
    `# ESPHome secrets for ${m.device.friendly_name}`,
    `# Generated by MajiFlow. Wifi is NOT here — it is provisioned on the device`,
    `# (captive portal / improv) and stored in its own flash (NVS).`,
    ``,
    `ota_password: "${s.ota_password}"`,
    `mqtt_token: "${s.mqtt_token}"`,
    `udp_key: "${s.udp_key}"`,
    ``,
  ].join("\n");
}

function generateMetadataYaml(m: Manifest, metadata: GenerationMetadata): string {

  const lines: string[] = [];
  lines.push(`# =============================================================================`);
  lines.push(`# MajiFlow — Fleet Metadata Sensors`);
  lines.push(`# =============================================================================`);
  lines.push(`# Embedded provenance for drift detection and fleet management.`);
  lines.push(`# These sensors publish as diagnostic telemetry.`);
  lines.push(`# =============================================================================`);
  lines.push(``);

  // text_sensor block
  lines.push(`text_sensor:`);
  lines.push(`  - platform: template`);
  lines.push(`    id: majiflow_config_sha`);
  lines.push(`    name: "MajiFlow Config SHA"`);
  lines.push(`    entity_category: diagnostic`);
  lines.push(`    lambda: return "${metadata.configSha}";`);
  lines.push(``);
  lines.push(`  - platform: template`);
  lines.push(`    id: majiflow_generation_version`);
  lines.push(`    name: "MajiFlow Generation"`);
  lines.push(`    entity_category: diagnostic`);
  lines.push(`    lambda: return "${metadata.version}";`);
  lines.push(``);
  lines.push(`  - platform: template`);
  lines.push(`    id: majiflow_site_id`);
  lines.push(`    name: "MajiFlow Site"`);
  lines.push(`    entity_category: diagnostic`);
  lines.push(`    lambda: return "${metadata.siteId}";`);
  lines.push(``);
  lines.push(`  - platform: template`);
  lines.push(`    id: majiflow_controller_id`);
  lines.push(`    name: "MajiFlow Controller"`);
  lines.push(`    entity_category: diagnostic`);
  lines.push(`    lambda: return "${metadata.controllerId}";`);
  lines.push(``);

  lines.push(`  - platform: template`);
  lines.push(`    id: majiflow_device_name`);
  lines.push(`    name: "MajiFlow Device Name"`);
  lines.push(`    entity_category: diagnostic`);
  lines.push(`    lambda: return "${m.device.name}";`);
  lines.push(``);

  // sensor block
  lines.push(`sensor:`);
  lines.push(`  - platform: template`);
  lines.push(`    id: majiflow_build_timestamp`);
  lines.push(`    name: "MajiFlow Build Time"`);
  lines.push(`    entity_category: diagnostic`);
  lines.push(`    unit_of_measurement: "timestamp"`);
  lines.push(`    lambda: return ${metadata.buildTimestamp};`);
  lines.push(``);
  lines.push(`  - platform: template`);
  lines.push(`    id: majiflow_schema_version`);
  lines.push(`    name: "MajiFlow Schema"`);
  lines.push(`    entity_category: diagnostic`);
  lines.push(`    lambda: return ${metadata.schemaVersion};`);
  lines.push(``);
  lines.push(`  - platform: template`);
  lines.push(`    id: majiflow_route_count`);
  lines.push(`    name: "MajiFlow Routes"`);
  lines.push(`    entity_category: diagnostic`);
  lines.push(`    lambda: return ${m.routes.length};`);
  lines.push(``);
  lines.push(`  - platform: template`);
  lines.push(`    id: majiflow_node_count`);
  lines.push(`    name: "MajiFlow Nodes"`);
  lines.push(`    entity_category: diagnostic`);
  lines.push(`    lambda: return ${m.nodes.length};`);
  lines.push(``);

  return lines.join("\n");
}

/**
 * Returns the relative path prefix for everything a site generates.
 * `sites/{siteId}/...` is the single root for site-scoped artifacts:
 *   - `esphome/{deviceDir}/...`     — ESPHome firmware
 *   - `site-documentation.html`     — generated docs
 *
 * Self-test artifacts live in a separate `selftest/{model}/` tree and bypass
 * this prefix entirely — they are not site-scoped.
 */
export function siteRoot(siteId: string): string {
  return `sites/${siteId}`;
}

/**
 * Mark every emitted ESPHome entity `internal: true` in one post-pass.
 *
 * ESPHome auto-publishes each named entity's state to `<topic_prefix>/…/esphome/*`
 * on every update. Nothing reads that stream — the server ingests only our telemetry
 * lambda's topics (telemetry/event/status/identity); it's a vestige of the removed HA
 * model and the duplicate publish was overflowing the device's MQTT outbox on weak
 * links. `internal` stops that auto-publish while leaving the component fully usable
 * via id() (telemetry lambda, control logic, OLED); paired with
 * `web_server: include_internal: true` the states stay visible on the device's local
 * web page. Done as a single pass so the flag isn't threaded through every emitter.
 *
 * Only top-level entity sections are touched. Infrastructure (output/i2c/spi/display/…)
 * is skipped via section-gating; multi-sensor platforms (wifi_info/ethernet_info — whose
 * `internal` belongs on their sub-sensors, and which publish only on connect) are left
 * alone (extend MULTI_SENSOR_PLATFORMS when adding any platform that emits sub-sensors,
 * e.g. bme280); and block-scalar bodies (`lambda: |-` C++) are skipped so a `- platform:`
 * inside a lambda can't be mistaken for an entity declaration.
 */
const INTERNAL_ENTITY_SECTIONS = new Set([
  'sensor', 'binary_sensor', 'text_sensor', 'switch', 'cover', 'number', 'button',
]);
const MULTI_SENSOR_PLATFORMS = new Set(['wifi_info', 'ethernet_info']);

function internalizeEntities(yaml: string): string {
  const out: string[] = [];
  let inEntitySection = false;
  let scalarIndent = -1; // indent of the key owning an open block scalar; -1 = none
  for (const line of yaml.split('\n')) {
    const indent = line.search(/\S/);
    // A block scalar body ends when a non-blank line dedents to/under its owner key.
    if (scalarIndent >= 0 && indent >= 0 && indent <= scalarIndent) scalarIndent = -1;
    const section = /^([a-zA-Z_]\w*):\s*$/.exec(line);
    if (section) { inEntitySection = INTERNAL_ENTITY_SECTIONS.has(section[1]); scalarIndent = -1; }
    out.push(line);
    if (scalarIndent >= 0) continue; // inside a lambda/block-scalar body — never an entity
    // Opening a block scalar (`key: |-`, `key: >` …)? Skip its body on following lines.
    const scalar = /^(\s*)\S.*:\s*[|>][+-]?\s*$/.exec(line);
    if (scalar) { scalarIndent = scalar[1].length; continue; }
    if (!inEntitySection) continue;
    const plat = /^(\s*)- platform:\s*(\S+)/.exec(line);
    if (plat && !MULTI_SENSOR_PLATFORMS.has(plat[2])) {
      out.push(`${plat[1]}  internal: true`);
    }
  }
  return out.join('\n');
}

export async function generateEsphome(
  m: Manifest,
  board: BoardDef,
  siteId: string,
  secrets: SecretsMap | undefined,
  metadata: GenerationMetadata,
  expansionBoards: ExpansionBoardCatalog,
  options?: GenerateOptions,
): Promise<GeneratedFile[]> {
  const dir = m.device.directory ?? m.device.name;
  const deviceDir = `${siteRoot(siteId)}/esphome/${dir}`;
  const collected = collectEntityCodegen(m, board, expansionBoards, metadata);
  // Panel buttons — null on boards without input expanders; the device YAML
  // gates its package include on the matching hasLocalInputs predicate.
  const localInputs = generateLocalInputs(m, board);
  // On-device operator dashboard (maji_local_ui) — swaps web_server v3 for a bare
  // web_server_base the component serves on, and adds the package + app bundle below.
  const localUi = m.device.local?.ui === true;
  // Async: the asset table is read from the device-ui manifest (disk under Node,
  // HTTP fetch in the browser bundle).
  const localUiAssets = localUi
    ? options?.localUiAssetsHeader ?? await generateLocalUiAssetsHeader(m, options?.topologyJson)
    : undefined;

  const files: GeneratedFile[] = [
    {
      relativePath: `${deviceDir}/common/board.yaml`,
      description: `${board.label} board package (buses, battery, LED, diagnostics)`,
      content: internalizeEntities(generateBoardPackage(board, m.device.network, localUi)),
    },
    {
      relativePath: `${deviceDir}/common/images/logo.svg`,
      description: "Logo image for OLED splash screen",
      content: LOGO_SVG,
    },
    {
      relativePath: `${deviceDir}/${dir}.yaml`,
      description: "Device config (substitutions, boot, OLED display)",
      content: internalizeEntities(generateDeviceYaml(board, m, collected, metadata)),
    },
    {
      relativePath: `${deviceDir}/secrets.yaml`,
      description: "WiFi + OTA credentials",
      content: generateSecretsYaml(m, secrets),
    },
    {
      relativePath: `${deviceDir}/packages/control.yaml`,
      description: "State machine + safety watchdog",
      content: generateControl(m),
    },
    {
      relativePath: `${deviceDir}/packages/mqtt.yaml`,
      description: "MQTT runtime: telemetry publish, command subscribe, status",
      content: generateMqtt(m, metadata, board, localUi),
    },
    ...(localUi ? [{
      relativePath: `${deviceDir}/packages/local-ui.yaml`,
      description: "On-device operator dashboard (maji_local_ui endpoints + handler glue)",
      content: generateLocalUiYaml(m),
    }, {
      relativePath: `${deviceDir}/packages/local-ui-assets.h`,
      description: "Device-mode app assets (gzipped PROGMEM table from the device-ui manifest + /topology.json; placeholder page when the manifest is absent)",
      content: localUiAssets!,
    }] : []),
    {
      relativePath: `${deviceDir}/packages/route-engine.yaml`,
      description: "Route control engine config (route table + entity bindings for maji_control)",
      content: generateMajiControlConfig(m),
    },
    {
      relativePath: `${deviceDir}/packages/automation-engine.yaml`,
      description: "Runtime automation engine config (maji_automations table + 5s tick interval)",
      content: generateAutomationEngineConfig(m),
    },
    {
      relativePath: `${deviceDir}/packages/coordination.yaml`,
      description: "Cross-controller coordination over UDP (maji_coord/maji_claims config, on_receive dispatch, reading broadcast)",
      content: generateCoordination(m, metadata),
    },
    {
      relativePath: `${deviceDir}/packages/time-sync.h`,
      description: "C++ persisted-clock boot seed (wall-clock estimate across reboots; RTC overrides when fitted)",
      content: generateTimeSyncHeader(metadata),
    },
    {
      relativePath: `${deviceDir}/packages/time-sync.yaml`,
      description: "Persisted wall clock: flash-restored epoch + refresh interval",
      content: generateTimeSync(),
    },
    {
      relativePath: `${deviceDir}/packages/hardware.yaml`,
      description: "Pump relay, valve switches + covers",
      content: internalizeEntities(generateHardware(m, collected)),
    },
    ...(localInputs ? [{
      relativePath: `${deviceDir}/packages/local-inputs.yaml`,
      description: "Panel buttons on the board's digital inputs (route start / stop all)",
      content: internalizeEntities(localInputs),
    }] : []),
    {
      relativePath: `${deviceDir}/packages/sensors.yaml`,
      description: "Flow sensors, tank levels, calibration, state text",
      content: internalizeEntities(generateSensors(m, collected)),
    },
    {
      relativePath: `${deviceDir}/packages/metadata.yaml`,
      description: "Fleet metadata sensors (SHA, version, build timestamp)",
      content: internalizeEntities(generateMetadataYaml(m, metadata)),
    },
    {
      relativePath: `${deviceDir}/compile.sh`,
      description: "One-shot helper: compile / flash / tail logs via ESPHome",
      content: generateCompileScript(dir),
    },
    {
      relativePath: `${deviceDir}/requirements.txt`,
      description: "Pinned ESPHome version for a reproducible build (the bundle's external_components bind to its C++ API)",
      content: `esphome==${ESPHOME_VERSION}\n`,
    },
  ];

  // Vendored ESPHome external_components (maji_coord/maji_claims), referenced by the
  // device YAML's `external_components: source: local`. Source of truth is
  // firmware/components/**; FIRMWARE_COMPONENT_FILES is the generated browser-shippable mirror.
  for (const f of FIRMWARE_COMPONENT_FILES) {
    files.push({
      relativePath: `${deviceDir}/external_components/${f.path}`,
      description: `ESPHome external component source (${f.path})`,
      content: f.content,
    });
  }

  return files;
}

/**
 * Emits a self-contained helper script placed alongside the device YAML so a
 * user can build and flash without remembering ESPHome invocations. Run it from
 * the unzipped bundle:  `bash compile.sh`  (or `compile|flash|upload|logs`).
 */
function generateCompileScript(dir: string): string {
  const device = `${dir}.yaml`;
  return [
    `#!/usr/bin/env bash`,
    `# Generated by MajiFlow — build & flash this device's ESPHome firmware.`,
    `# Usage: bash compile.sh [compile|flash|upload|logs|ota]   (default: compile)`,
    `#   ota — compile, then isolate the built image to ./ota/ for OTA upload.`,
    `set -euo pipefail`,
    `cd "$(dirname "$0")"`,
    ``,
    `# ESP-IDF / PlatformIO refuse to build from a path containing a space.`,
    `# Catch it here with a clear message instead of a cryptic toolchain error`,
    `# (a common cause: the browser saved a duplicate download as "name (2)").`,
    `if printf '%s' "$PWD" | grep -q '[[:space:]]'; then`,
    `  echo "ERROR: this firmware folder sits in a path that contains a space:" >&2`,
    `  echo "  $PWD" >&2`,
    `  echo "ESP-IDF cannot build there. Move it to a path with no spaces and re-run, e.g.:" >&2`,
    `  echo "  mv THIS_FOLDER ~/majiflow-firmware && cd ~/majiflow-firmware && bash compile.sh" >&2`,
    `  exit 1`,
    `fi`,
    ``,
    `DEVICE="${device}"`,
    ``,
    `if ! command -v esphome >/dev/null 2>&1; then`,
    `  echo "esphome not found. Install the pinned version with:  pip install -r requirements.txt" >&2`,
    `  echo "(see https://esphome.io/guides/installing_esphome )" >&2`,
    `  exit 1`,
    `fi`,
    ``,
    `# Soft version check — the bundled external_components bind to ESPHome's C++ API.`,
    `PINNED="${ESPHOME_VERSION}"`,
    `have="$(esphome version 2>/dev/null | sed -nE 's/^Version:[[:space:]]*([0-9.]+).*/\\1/p')"`,
    `if [ -n "$have" ] && [ "$have" != "$PINNED" ]; then`,
    `  echo "WARNING: esphome $have installed, but this bundle was generated for $PINNED." >&2`,
    `  echo "         If the build fails, run:  pip install -r requirements.txt" >&2`,
    `fi`,
    ``,
    `cmd="\${1:-compile}"`,
    `case "$cmd" in`,
    `  compile) esphome compile "$DEVICE" ;;        # build the firmware binary`,
    `  flash)   esphome run "$DEVICE" ;;            # build + upload (USB or OTA)`,
    `  upload)  esphome upload "$DEVICE" ;;         # upload an existing build`,
    `  logs)    esphome logs "$DEVICE" ;;           # tail device logs`,
    `  ota)`,
    `    # Build, then isolate the OTA image so you know exactly which file to upload`,
    `    # on the Deploy page. ESPHome has no stable "print the bin path" command, so`,
    `    # we glob the newest firmware.ota.bin under the build tree.`,
    `    esphome compile "$DEVICE"`,
    `    name="\${DEVICE%.yaml}"`,
    `    # esphome names the build dir after the device's 'name:' field (lowercased and`,
    `    # hyphenated), which can differ from this yaml's filename — so glob both levels`,
    `    # rather than assuming the dir matches "$name".`,
    `    bin="$(ls -t .esphome/build/*/.pioenvs/*/firmware.ota.bin 2>/dev/null | head -n1 || true)"`,
    `    if [ -z "$bin" ]; then`,
    `      echo "ERROR: no firmware.ota.bin found under .esphome/build/ — did the compile above succeed?" >&2`,
    `      exit 1`,
    `    fi`,
    `    ver="$(grep -A3 'id: majiflow_generation_version' packages/metadata.yaml | grep -m1 'lambda: return' | sed -E 's/.*return "([^"]*)".*/\\1/' || true)"`,
    `    mkdir -p ota`,
    `    out="ota/$name\${ver:+-$ver}.bin"`,
    `    cp "$bin" "$out"`,
    `    echo "OTA image ready:  $out"`,
    `    echo "Version:          \${ver:-unknown}"`,
    `    echo "Upload this file on the Deploy page, then click 'Deploy to device'."`,
    `    ;;`,
    `  *) echo "usage: bash compile.sh [compile|flash|upload|logs|ota]" >&2; exit 2 ;;`,
    `esac`,
    ``,
  ].join("\n");
}

/**
 * Generate firmware files for a manifest + board using the specified backend.
 */
export async function generateFirmware(
  generator: GeneratorId,
  manifest: Manifest,
  board: BoardDef,
  siteId: string,
  secrets: SecretsMap | undefined,
  metadata: GenerationMetadata,
  expansionBoards: ExpansionBoardCatalog,
  options?: GenerateOptions,
): Promise<GeneratedFile[]> {
  if (generator === 'esphome') {
    return generateEsphome(manifest, board, siteId, secrets, metadata, expansionBoards, options);
  }
  throw new Error(`Unknown generator: ${generator}`);
}

export async function generateAll(
  m: Manifest,
  board: BoardDef,
  siteId: string,
  secrets: SecretsMap | undefined,
  metadata: GenerationMetadata,
  expansionBoards: ExpansionBoardCatalog,
  options?: GenerateOptions,
): Promise<GeneratedFile[]> {
  return [...(await generateFirmware('esphome', m, board, siteId, secrets, metadata, expansionBoards, options))];
}
